version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build_macos:
    executor:
      name: node/default
    steps:
    - checkout
    - node/with-cache:
        steps:
        - run: npm install
        - run: npm run release mac
workflows:
  build:
    jobs:
    - build_macos
